---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь может добавить товар в корзину и продолжить выбирать товары в каталоге
  -На странице корзины пользователь может удалить товар из корзины, продолжить выбирать товары в каталоге, оформить заказ с переходом на страницу оплаты
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - На странице товара и в каталоге выводятся название, рейтинг, цена со скидкой и без
  - Корзина хранится в сессии браузера
implicit:
  - Должна быть возможность оставлять отзыв на товар
  - Должна быть возможность оставить оценку на товар
  - Должна быть возможность изменять валюту (доллары, рубли, евро)
  - Должна быть возможность указать количество добавляемого товара в корзину
  - Пользователь не может редактировать описание товара
  - Должна быть возможность перейти по хэштегу в карточке товара
